# Generated by Django 5.0.6 on 2024-06-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default=1, upload_to='static/fotos_clientes/'),
            preserve_default=False,
        ),
    ]
